import type { IntegrationCard, IntegrationSpec } from "@/lib/types";

export const NAV_ITEMS = [
  { key: "dashboard", label: "Dashboard" },
  { key: "clients", label: "Clients" },
  { key: "meetings", label: "Meetings" },
  { key: "wins", label: "Wins" },
  { key: "issues", label: "Issues" },
  { key: "recommendations", label: "Recommendations" },
  { key: "integrations", label: "Integrations" },
  { key: "wiki", label: "Wiki / Field Manual" },
] as const;

export const INTEGRATIONS: IntegrationCard[] = [
  {
    slug: "clickup",
    name: "ClickUp",
    category: "Project Mgmt",
    glyph: "CU",
    icon: ["rgba(124,58,237,.16)", "#a78bfa"],
    description: "Account activity, overdue tasks, ticket SLAs. Push action items back automatically.",
    scope: "user",
  },
  {
    slug: "ghl",
    name: "GoHighLevel",
    category: "CRM",
    glyph: "GHL",
    icon: ["rgba(245,165,36,.16)", "#f5a524"],
    description: "Pipelines, leads, comms history, appointments. Sync recap + tasks.",
    scope: "admin",
    sourceKey: "ghl",
  },
  {
    slug: "gads",
    name: "Google Ads",
    category: "Paid Media",
    glyph: "GA",
    icon: ["rgba(74,158,255,.16)", "#4a9eff"],
    description: "PPC metrics, conversions, budget pacing, optimization opportunities.",
    scope: "admin",
    sourceKey: "mcc",
  },
  {
    slug: "gbp",
    name: "Google Business Profile",
    category: "Local SEO",
    glyph: "GBP",
    icon: ["rgba(52,211,153,.16)", "#34d399"],
    description: "Calls, direction requests, reviews, local visibility deltas.",
    scope: "admin",
    sourceKey: "mcc",
  },
  {
    slug: "gcalendar",
    name: "Google Calendar",
    category: "Meetings",
    glyph: "GC",
    icon: ["rgba(74,158,255,.16)", "#4a9eff"],
    description: "Upcoming Monthly Touch meetings, calendar invites, attendees, and next-touch scheduling.",
    scope: "user",
  },
  {
    slug: "gdrive",
    name: "Google Drive",
    category: "Docs",
    glyph: "GD",
    icon: ["rgba(52,211,153,.16)", "#34d399"],
    description: "Client folders, recap docs, transcripts, agendas, and meeting artifacts linked into the OS.",
    scope: "user",
  },
  {
    slug: "ga4",
    name: "Google Analytics 4",
    category: "Analytics",
    glyph: "G4",
    icon: ["rgba(245,124,36,.16)", "#f59e36"],
    description: "Traffic, conversions, attribution, engagement summaries.",
    scope: "admin",
    sourceKey: "adg",
  },
  {
    slug: "gsc",
    name: "Google Search Console",
    category: "SEO",
    glyph: "SC",
    icon: ["rgba(74,158,255,.16)", "#4a9eff"],
    description: "Organic keywords, CTR, impressions, indexing health.",
    scope: "admin",
    sourceKey: "adg",
  },
  {
    slug: "ranktracker",
    name: "Map Ranking Rank Tracker",
    category: "Local SEO",
    glyph: "RT",
    icon: ["rgba(45,212,191,.16)", "#2dd4bf"],
    description: "Live business records, place IDs, and rank-tracker visibility inputs from the Map Ranking platform.",
    scope: "admin",
    sourceKey: "mrapi",
  },
  {
    slug: "mapcheckins",
    name: "Map Check-Ins",
    category: "Field Ops",
    glyph: "CI",
    icon: ["rgba(245,165,36,.16)", "#f5a524"],
    description: "Check-in coverage, frequency, and business activity pulled from the Map Ranking check-ins app.",
    scope: "admin",
    sourceKey: "mrapi",
  },
  {
    slug: "ahrefs",
    name: "Ahrefs",
    category: "SEO",
    glyph: "AH",
    icon: ["rgba(45,212,191,.16)", "#2dd4bf"],
    description: "Backlinks, keyword growth, competitor movement detection.",
    scope: "user",
  },
  {
    slug: "meta",
    name: "Meta Ads",
    category: "Paid Media",
    glyph: "M",
    icon: ["rgba(74,158,255,.16)", "#4a9eff"],
    description: "FB/IG ads, retargeting, lead gen, creative + ROAS insights.",
    scope: "user",
  },
  {
    slug: "gmail",
    name: "Gmail",
    category: "Comms",
    glyph: "@",
    icon: ["rgba(245,84,79,.16)", "#f5544f"],
    description: "Comm history, unresolved threads, AI follow-up drafts, sentiment.",
    scope: "user",
  },
  {
    slug: "meet",
    name: "Google Meet",
    category: "Meetings",
    glyph: "GM",
    icon: ["rgba(52,211,153,.16)", "#34d399"],
    description: "Recordings + transcripts feeding the recap and content extractor.",
    scope: "user",
  },
];

export const ADMIN_SOURCES = {
  mcc: {
    label: "Google MCC",
    hint: "mcc@mapranking.com",
    provider: "Google",
    glyph: "MCC",
    icon: ["rgba(74,158,255,.16)", "#4a9eff"] as [string, string],
    description: "Manager account — every client location and ad account lives here.",
    covers: ["gads", "gbp"],
  },
  adg: {
    label: "Agency Google Account",
    hint: "analytics@mapranking.com",
    provider: "Google",
    glyph: "G",
    icon: ["rgba(245,124,36,.16)", "#f59e36"] as [string, string],
    description: "Analytics 4 + Search Console across the entire book.",
    covers: ["ga4", "gsc"],
  },
  mrapi: {
    label: "Map Ranking Ops API",
    hint: "dashboardapi.mapranking.com",
    provider: "Map Ranking",
    glyph: "MR",
    icon: ["rgba(45,212,191,.16)", "#2dd4bf"] as [string, string],
    description: "Shared API tokens for rank tracker and map check-ins business datasets.",
    covers: ["ranktracker", "mapcheckins"],
  },
  ghl: {
    label: "GoHighLevel — Agency",
    hint: "agency@mapranking.com",
    provider: "GoHighLevel",
    glyph: "GHL",
    icon: ["rgba(245,165,36,.16)", "#f5a524"] as [string, string],
    description: "Agency-level token, all sub-accounts inherited.",
    covers: ["ghl"],
  },
} as const;

export const INTEGRATION_SPECS: Record<string, IntegrationSpec> = {
  clickup: {
    auth: "OAuth 2.0 app (authorization code)",
    base: "https://api.clickup.com/api/v2",
    frequency: "Hourly + webhook",
    scopes: ["read tasks", "read lists", "write tasks", "read time tracking"],
    endpoints: [
      { method: "GET", path: "/team", description: "Load available workspaces for the connected manager." },
      { method: "GET", path: "/list/{list_id}/task", description: "Read the Client Health Tracker rows and related tasks." },
      { method: "POST", path: "/list/{list_id}/task", description: "Push action items back after a meeting." },
    ],
    feeds: ["Recent activity feed", "Overdue-task flags", "Account health delivery status", "Action-item push"],
    automation:
      "Filters the Client Health Tracker to only the signed-in manager’s rows, then syncs normalized client records into the OS.",
  },
  ghl: {
    auth: "OAuth 2.0 marketplace app",
    base: "https://services.leadconnectorhq.com",
    frequency: "15 min + webhook",
    scopes: ["contacts.readonly", "opportunities.readonly", "conversations.readonly", "workflows.write"],
    endpoints: [
      { method: "POST", path: "/opportunities/search", description: "Pipeline stages, values, and lead counts." },
      { method: "GET", path: "/conversations/search", description: "SMS/email/call history for sentiment." },
    ],
    feeds: ["Pipeline value + lead counts", "Comms history -> sentiment", "Next-touch sync", "Recap write-back"],
    automation: "Pulls pipeline + comms for the brief and writes recap, sentiment, and next touch back to the CRM.",
  },
  gads: {
    auth: "OAuth 2.0 + developer token",
    base: "https://googleads.googleapis.com/v17",
    frequency: "Daily",
    scopes: ["https://www.googleapis.com/auth/adwords"],
    endpoints: [{ method: "POST", path: "/customers/{id}/googleAds:searchStream", description: "GAQL metrics and conversions." }],
    feeds: ["Paid leads + CPL", "Ad spend + pacing", "Conversion tracking"],
    automation: "Detects budget pacing and CPL swings, then surfaces them as wins or flagged issues.",
  },
  gbp: {
    auth: "OAuth 2.0",
    base: "https://businessprofileperformance.googleapis.com/v1",
    frequency: "Daily",
    scopes: ["https://www.googleapis.com/auth/business.manage"],
    endpoints: [{ method: "GET", path: "/locations/{id}:getDailyMetricsTimeSeries", description: "Calls, directions, website clicks." }],
    feeds: ["GBP calls", "Direction requests", "Reviews + rating"],
    automation: "Aggregates monthly local-performance deltas directly into the wins block.",
  },
  gcalendar: {
    auth: "OAuth 2.0",
    base: "https://www.googleapis.com/calendar/v3",
    frequency: "Near real time",
    scopes: ["https://www.googleapis.com/auth/calendar.readonly"],
    endpoints: [{ method: "GET", path: "/calendars/primary/events", description: "Upcoming Monthly Touch meetings and attendees." }],
    feeds: ["Upcoming meetings", "Last meeting date", "Next touch scheduling"],
    automation: "Pulls each manager’s live meeting calendar into the app so next touches and meeting cadence stay current.",
  },
  gdrive: {
    auth: "OAuth 2.0",
    base: "https://www.googleapis.com/drive/v3",
    frequency: "Near real time",
    scopes: ["https://www.googleapis.com/auth/drive.readonly"],
    endpoints: [{ method: "GET", path: "/files", description: "Client recaps, transcripts, agendas, and meeting docs." }],
    feeds: ["Recap docs", "Agenda templates", "Transcript files", "Meeting artifacts"],
    automation: "Finds the latest client-facing docs in Drive and links them into the meeting workflow without fallback content.",
  },
  ga4: {
    auth: "OAuth 2.0",
    base: "https://analyticsdata.googleapis.com/v1beta",
    frequency: "Daily",
    scopes: ["https://www.googleapis.com/auth/analytics.readonly"],
    endpoints: [{ method: "POST", path: "/properties/{id}:runReport", description: "Sessions, conversions, and engagement." }],
    feeds: ["Website sessions", "Conversions + rate", "Engagement"],
    automation: "Summarizes traffic and conversion trends in client-friendly language for the brief.",
  },
  gsc: {
    auth: "OAuth 2.0",
    base: "https://www.googleapis.com/webmasters/v3",
    frequency: "Daily",
    scopes: ["https://www.googleapis.com/auth/webmasters.readonly"],
    endpoints: [{ method: "POST", path: "/sites/{siteUrl}/searchAnalytics/query", description: "Clicks, impressions, CTR, position." }],
    feeds: ["Organic clicks + impressions", "CTR", "Keyword movement"],
    automation: "Flags keyword gains and losses and ranks them for meeting talking points.",
  },
  ranktracker: {
    auth: "Bearer API token",
    base: "https://dashboardapi.mapranking.com",
    frequency: "Daily",
    scopes: ["business.read", "rank-tracker.read"],
    endpoints: [{ method: "GET", path: "/api/business/get-business", description: "Business roster, place IDs, and live platform status." }],
    feeds: ["Business records", "Place IDs", "Rank tracker coverage"],
    automation: "Matches Map Ranking business records against synced clients so the OS can enrich local SEO context from live platform data.",
  },
  mapcheckins: {
    auth: "Bearer API token",
    base: "https://dashboardapi.mapranking.com",
    frequency: "Daily",
    scopes: ["checkins.read"],
    endpoints: [{ method: "GET", path: "/api/checkin-business/get-business-paginated", description: "Business check-in coverage and activity." }],
    feeds: ["Check-in coverage", "Business activity", "Location proof readiness"],
    automation: "Pulls live check-in business records into the OS so managers can see location activity without relying on demo placeholders.",
  },
  ahrefs: {
    auth: "Bearer API token",
    base: "https://api.ahrefs.com/v3",
    frequency: "Weekly",
    scopes: ["site-explorer", "rank-tracker"],
    endpoints: [{ method: "GET", path: "/site-explorer/overview", description: "Domain rating and backlink growth." }],
    feeds: ["Backlink growth", "Organic keyword count", "Competitor movement"],
    automation: "Turns keyword and backlink gains into strategy notes and expansion opportunities.",
  },
  meta: {
    auth: "OAuth 2.0 system user token",
    base: "https://graph.facebook.com/v19.0",
    frequency: "Daily",
    scopes: ["ads_read", "business_management"],
    endpoints: [{ method: "GET", path: "/act_{id}/insights", description: "Spend, ROAS, leads, reach, CPM." }],
    feeds: ["Spend + ROAS", "Lead gen + quality", "Reach"],
    automation: "Surfaces top-performing creative and ROAS shifts as wins or optimization moves.",
  },
  gmail: {
    auth: "OAuth 2.0",
    base: "https://gmail.googleapis.com/gmail/v1",
    frequency: "15 min",
    scopes: ["https://www.googleapis.com/auth/gmail.readonly"],
    endpoints: [{ method: "GET", path: "/users/me/messages", description: "Communication history and unresolved threads." }],
    feeds: ["Comm history", "Unresolved threads", "Email sentiment"],
    automation: "Reads sentiment and open threads, then drafts follow-ups for human review.",
  },
  meet: {
    auth: "OAuth 2.0",
    base: "https://meet.googleapis.com/v2",
    frequency: "On meeting end",
    scopes: ["https://www.googleapis.com/auth/meetings.space.readonly", "drive.readonly"],
    endpoints: [{ method: "GET", path: "/conferenceRecords/{id}/transcripts", description: "Transcript entries for recap generation." }],
    feeds: ["Meeting transcripts", "AI recap input", "Action-item extraction"],
    automation: "Routes the transcript into recap and content extraction workflows as soon as the meeting ends.",
  },
};

export const FIELD_MANUAL = [
  {
    category: "Account Management · Field Manual",
    title: "The Monthly Touch Meeting Operating System",
    intro:
      "How we turn a recurring reporting call into a strategic, retention-building business conversation every month with minimal prep and maximum consistency.",
    sections: [
      "Clients rarely churn over a single bad metric. They churn when the value becomes invisible, meetings feel repetitive, or a problem surfaces they feel should have been flagged sooner.",
      "Every meeting must leave the client informed, involved, confident, supported, and captured.",
      "Each cycle follows four phases: prep, meeting, recap, and follow-through.",
      "Prep time target is under 10 minutes per client. If it takes longer, the integration is incomplete.",
      "Every meeting opens with wins, surfaces issues proactively, lands on strategy, and closes with owned action items.",
    ],
  },
  {
    category: "Playbook",
    title: "The 60-Minute Meeting Structure",
    intro: "A consistent flow keeps the account manager in control and the client engaged.",
    sections: [
      "0–5: open and rapport.",
      "5–8: align on the agenda.",
      "8–20: lead with three wins tied to business goals.",
      "20–32: surface two issues and explain what is already underway.",
      "32–48: shift into strategic recommendations and next priorities.",
      "48–53: make the testimonial or content ask when sentiment is positive.",
      "53–60: confirm action items, owners, dates, and the next touch.",
    ],
  },
];
